---
- name: Shutdown
  hosts: ubuntu
  become: true
  become_method: sudo
  gather_facts: false
  tasks:
    - name: Shutdown
      ansible.builtin.command: /sbin/poweroff

    - name: Wait_to_shutdown
      ansible.builtin.wait_for:
        port: 22
#        delay: 10
        state: stopped
      delegate_to: localhost
